#!/usr/local/bin/bash

BASE="/home/ghz/wx/power"
DATA_D="$BASE/data"
PLOTS_D="$BASE/plots"
LOCK="$BASE/LOCK.power"
TD="$BASE/data/last48h"
HOST="probe0"
DATEB=/home/ghz/wx/particle/fbsd_date/date

cd $DATA_D ||exit 1
cd $PLOTS_D ||exit 1

[ -e $LOCK ] && {
	echo "oh lock noes"
	exit 1
}

touch $LOCK

DC=`date +%C`
DATE=`date +%Y%m%d`
DATE24H=`$DATEB -v-24H +%Y%m%d%H`
YDATE=`$DATEB -v-1d +%Y%m%d`
YYDATE=`$DATEB -v-2d +%Y%m%d`
YYDATEH=`$DATEB -v-2d +%Y%m%d%H`

PAT0='[0-9]{3,4}\.[0-9]{2}mV [0-9]{3,4}\.[0-9]{2}mV [0-9]{2,4}\.[0-9]{2}mV -?[0-9]{1,3}\.[0-9]{2}C END$'
PAT1="^$DC([0-9]{12}) $PAT0"

TD_DUMP="cat $DATA_D/$YYDATE $DATA_D/$YDATE $DATA_D/$DATE"

TDAT=`wget -qT 16 -t 1 probe0 -O - | tr -d '\r' | egrep "^$PAT0"` || {
	rm $LOCK
	exit 1
}

(date +%Y%m%d%H%M%S; echo $TDAT) |paste -d ' ' - - | egrep "$PAT1" >> $DATA_D/$DATE

$TD_DUMP | grep -A 4000 $YYDATEH | egrep "$PAT1" > $TD || $TD_DUMP | egrep "$PAT1" > $TD

$BASE/gen_index

# Current Transformers floating at 1017mVDC
# ADC's see 1029mVDC when current probes are in free space. or as free space as i can get.
# so we'll start our base there

# Best guess to date (20121009) is that we see .046 A thru the primary for every 1 mV of output from the current probe.
# Presently, our line voltage measures at 120.5 V. your know. ish.
# thus we take output in mV * .046 A/mV * 120.5 V => output(mV) * 5.543 W/mv to get power in watts from probe output in mV.
# probably.

POWER[0]="\"$TD\" using 1:((\$2-1029)*5.543) title 'Power Use (phase 0, Watts)' with lines linecolor rgb \"#00ff00\""
POWER[1]="\"$TD\" using 1:((\$3-1029)*5.543) title 'Power Use (phase 1, Watts)' with lines linecolor rgb \"#00ffff\""
POWER_TOT="\"$TD\" using 1:((\$2+\$3-2058)*5.543) title 'Power Use (phase 0 + 1, Watts)' with lines linecolor rgb \"#0000ff\"" 
TEMP="\"$TD\" using 1:5 title 'Temp (C)' with lines lt 1"

PROLOUGE="set title \"Power Utilization for the Last ~48 Hours\";\
	set xtics 7200 ;\
	set y2tics ;\
	set key outside below;\
	set xlabel \"Time (UTC)\" offset 0.0, -1.0;\
	set ylabel \"Power Use (Watts)\";\
	set y2label \"Power Use (Watts)\";\
	set xdata time;\
	set format x \"%m/%d\\n%H:%M\";\
	set timefmt \"%Y%m%d%H%M%S\";\
	set grid;\
	set term png size 4000, 512  font \",10\";"

echo "$PROLOUGE\
        set output 'all.png';\
        plot ${POWER[0]}, ${POWER[1]}, $POWER_TOT;\
        " |gnuplot

echo "$PROLOUGE\
        set output 'total.png';\
        plot $POWER_TOT;\
        " |gnuplot

for((i=0;i<=1;i++)); do {
echo "$PROLOUGE\
	set output 'power_$i.png';\
	plot ${POWER[$i]};\
	" |gnuplot
} done

echo "$PROLOUGE\
	set title \"Panel Temperature for the Last ~24 Hours\";\
	set ylabel \"Deg (C)\";\
	set y2label \"Deg (C)\";\
	set output 'temp.png';\
	plot $TEMP;\
	" |gnuplot

cp $PLOTS_D/*.png $BASE/power.html /wx/power/

rsync -u $BASE/powerscript $BASE/gen_index $BASE/etherpower.pde /wx/power/

rsync -qu $DATA_D/* /wx/power/data/

rm $LOCK
